### ISSUE TITLE
Coercing to numeric is dropping the formatting `round_transforming()`

### ISSUE THREAD

**Issue by paddytobias** [socialresearchcentre/projectable#30]
There's a bit in `round_transformer()` which coerces the value to numeric if it can:

https://github.com/socialresearchcentre/projectable/blob/0497294b9b475e061411680ecf20e4c41ae618b0/R/prj_project.R#L142

This is causing the specific formatting to be dropped. E.g., "10.10" is coming through as "10.1" which isn't desirable as there's specific formatting needed in the national reports depending if it is internal or public - public rounds to 1 decimal and is padded out if it's a whole number. 

I've picked this up in GOSL tabling

I suggest we remove the coercing that's happening here, what do you think @kinto-b @TirdadSRC? I think the formatting should be controlled by the functions like `dec_dig3()` etc.

**Comment by paddytobias** [comment]
For example, with the coercion: 

``` r
library(srcreporting)
library(projectable)

dat <- prj_tbl_rows(mtcars,
                    Cylinders = cyl,
                    Transmission = list(Automatic = am %in% 0, Manual = am %in% 1),
)

dat <- prj_tbl_summarise(
  prj_tbl_cols(dat,
               `V-Shaped` = col_freq(n = vs %in% 1, N = vs %in% 0:1),
               `Not V-shaped` = col_freq(n = vs %in% 0, N = vs %in% 0:1)
  ))




prj_project(
  dat, list(
    `V-Shaped` = c(p = "{srcreporting::dec_dig3(p, 2)} ({n})"),
    `Not V-shaped` = c(p = "{srcreporting::dec_dig3(p, 2)} ({n})")
  )
)
#> Warning in prj_cast_shadow(.data, .digits = .digits): 
#> Column name duplicated: `p`
#> Resolving by incrementing...
#> # A tibble: 5 x 4
#>   row_spanner  rows      p1        p2       
#> * <col_row>    <col_row> <glue>    <glue>   
#> 1 Cylinders    4         0.91 (10) 0.09 (1) 
#> 2 Cylinders    6         0.57 (4)  0.43 (3) 
#> 3 Cylinders    8         0 (0)     1 (14)   
#> 4 Transmission Automatic 0.37 (7)  0.63 (12)
#> 5 Transmission Manual    0.54 (7)  0.46 (6)
```

<sup>Created on 2022-05-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Versus, no coercion: 

``` r
library(srcreporting)
library(projectable)

dat <- prj_tbl_rows(mtcars,
                    Cylinders = cyl,
                    Transmission = list(Automatic = am %in% 0, Manual = am %in% 1),
)

dat <- prj_tbl_summarise(
  prj_tbl_cols(dat,
               `V-Shaped` = col_freq(n = vs %in% 1, N = vs %in% 0:1),
               `Not V-shaped` = col_freq(n = vs %in% 0, N = vs %in% 0:1)
  ))




prj_project(
  dat, list(
    `V-Shaped` = c(p = "{srcreporting::dec_dig3(p, 2)} ({n})"),
    `Not V-shaped` = c(p = "{srcreporting::dec_dig3(p, 2)} ({n})")
  )
)
#> Warning in prj_cast_shadow(.data, .digits = .digits): 
#> Column name duplicated: `p`
#> Resolving by incrementing...
#> # A tibble: 5 x 4
#>   row_spanner  rows      p1        p2       
#> * <col_row>    <col_row> <glue>    <glue>   
#> 1 Cylinders    4         0.91 (10) 0.09 (1) 
#> 2 Cylinders    6         0.57 (4)  0.43 (3) 
#> 3 Cylinders    8         0.00 (0)  1.00 (14)
#> 4 Transmission Automatic 0.37 (7)  0.63 (12)
#> 5 Transmission Manual    0.54 (7)  0.46 (6)
```

<sup>Created on 2022-05-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by kinto-b** [comment]
@paddytobias You can turn off rounding by setting `digits=NULL`.  Try

```r
prj_project(
  dat, list(
    `V-Shaped` = c(p = "{srcreporting::dec_dig3(p, 2)} ({n})"),
    `Not V-shaped` = c(p = "{srcreporting::dec_dig3(p, 2)} ({n})")
  ), .digits = NULL
)
```

I added rounding as a default because I found myself writing `"{round(p, 2)}"` literally every time I did a projection. On net I think it saves more typing having the default this way rather than having `.digits=NULL` by default. 

One thing that would be neat though is to deprecate the `.digits` argument and replace with a `.format` argument which accepts a formatting function (i.e. a one place function that accepts a string and returns a string). By default `.format = round_transformer` but then you could write `.format = srcreporting::dec_dig3`

**Comment by paddytobias** [comment]
Thanks @kinto-b , that's a little hidden gem! And I can see you've got an option called "prj_digits" to control this in the global environment. All good then.

Yeah a `.format` argument could be good, to have greater oversight of the formatting. Gonna leave this for another day :)
